all:
	g++ -std=c++11 functor-example.cpp -o functor-example
	g++ -std=c++11 virtualfunction-example.cpp -o virtualfunction-example

functor-example:
	g++ -std=c++11 functor-example.cpp -o functor-example

virtualfunction-example:
	g++ -std=c++11 virtualfunction-example.cpp -o virtualfunction-example

clean:
	rm functor-example
	rm virtualfunction-example

